exchanges = ["Bitfinex",
             "Bittrex",
             "Binance",
             "Kraken",
             "Hitbtc",
             "Poloniex",
             "Huobipro",
             "Gdax",
             "Bitstamp",
             "Bitmex"]
symbols = [
    "ETH/BTC",
    "BCH/BTC", 
    "EOS/BTC",
    "XRP/BTC",
    "EOS/BTC",
    "LTC/BTC",
    "XLM/BTC",
    "ADA/BTC",
    "IOTA/BTC",
    "TRX/BTC",
    "XMR/BTC",
    "NEO/BTC",
    "DASH/BTC",
    "ETC/BTC",
    "XEM/BTC",
    "XTZ/BTC",
    "VEN/BTC",
    "OMG/BTC",
    "ZEC/BTC",
    "QTUM/BCT",
    "MIT/BTC",
    "SNT/BTC",
    "IOST/BTC",
    "LRC/BTC",
    "ZEN/BTC"
]
symbol_freq = 10 # seg
req_freq = 5 # seg
