exchanges = ["Bitfinex",
             "Bittrex",
             "Binance",
             "Kraken",
             "Hitbtc",
             "Poloniex",
             "Huobipro",
             "Gdax",
             "Bitstamp",
             "Bitmex"]
# symbols = [
#     "BTC/USD",
#     "BTC/USDT"
#     "BTC/EUR",
#     "ETH/USD",
#     "ETH/USDT",
#     "ETH/EUR",
#     "XRP/USD",
#     "XRP/USDT",
#     "XRP/EUR",
#     "BCH/USD",
#     "BCH/USDT",
#     "BCH/EUR",
#     "EOS/USD",
#     "EOS/USDT",
#     "EOS/EUR",
#     "LTC/USD",
#     "LTC/USDT",
#     "LTC/EUR",
#     "XLM/USD",
#     "XLM/USDT",
#     "XLM/EUR",
#     "ADA/USD",
#     "ADA/USDT",
#     "ADA/EUR",
# ]
symbols = [
    "BTC/USD",
    "BTC/USDT",
    "ETH/BTC",
    "BCH/BTC",
    "EOS/BTC",
    "XRP/BTC",
    "EOS/BTC",
    "LTC/BTC",
    "XLM/BTC",
    "ADA/BTC",
    "IOTA/BTC",
    "TRX/BTC",
    "XMR/BTC",
    "NEO/BTC",
    "DASH/BTC",
    "ETC/BTC",
    "XEM/BTC",
    "XTZ/BTC",
    "VEN/BTC",
    "OMG/BTC",
    "ZEC/BTC",
    "QTUM/BTC",
    "MIT/BTC",
    "SNT/BTC",
    "IOST/BTC",
    "LRC/BTC",
    "ZEN/BTC"
]
database = "sql" # "sql" - "nosql"
symbol_freq = 10 # seg
req_freq = 5 # seg
