exchanges = ["Bitfinex",
             "Bittrex",
             "Binance",
             "Kraken",
             "Hitbtc",
             "Poloniex" ,
             "Huobi",
             "Gdax",
             "Bitstamp",
             "Bitmex"]
symbols = ["BTC/USD",
           "BTC/EUR",
           "BTC/USDT",
           "ETH/USD",
           "ETH/EUR",
           "ETH/USDT",
           "BCH/USD",
           "BCH/EUR",
           "BCH/USDT",
           "LTC/USD",
           "LTC/USDT",
           "LTC/EUR",
           "EOS/USD",
           "EOS/USDT",
           "EOS/EUR"]
symbol_freq = 10 # seg
req_freq = 5 # seg
